apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-demo-dev

resources:
- ../../base
- configmap.yaml

images:
- name: aks-demo
  newName: craksdemodev.azurecr.io/aks-demo
  newTag: 7cc41b1

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: aks-demo
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.aksdemo.lenghel.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.aksdemo.lenghel.dev
    - op: replace
      path: /spec/tls/0/secretName
      value: dev-aksdemo-lenghel-dev-tls
  target:
    kind: Ingress
    name: aks-demo
