apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-demo

resources:
- ../../base
- configmap.yaml

images:
- name: aks-demo
  newName: craksdemodev.azurecr.io/aks-demo
  newTag: 57a2968

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: aks-demo
